echo Executing NeXTTool to upload /home/jmherruzo/LEGO/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
wineconsole /cygdrive/C/cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=/home/jmherruzo/LEGO/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
